CREATE DATABASE cine_polnito;

CREATE TABLE ESTADO(IDESTADO INT NOT NULL, NOMBRE VARCHAR(80) NOT NULL, POBLACION INT NULL);

SELECT* FROM ESTADO;

ALTER TABLE ESTADO ADD PRIMARY KEY (IDESTADO);

INSERT INTO ESTADO VALUES(1, 'CHIAPAS', 1500);

CREATE TABLE INDICADOR(IDINDICADOR INT NOT NULL, NOMBRE VARCHAR(80) NOT NULL, DESCRIPCION VARCHAR(80) NOT NULL, PRIMARY KEY(IDINDICADOR));

CREATE TABLE MUNICIPIO(IDMUNICIPIO INT NOT NULL, NOMBRE VARCHAR(80) NOT NULL, IDESTADO INT NOT NULL, PRIMARY KEY(IDMUNICIPIO), FOREIGN KEY(IDESTADO) REFERENCES ESTADO(IDESTADO));

CREATE TABLE MUNICIPIOINDICADOR(IDMUNICIPIOINDICADOR INT NOT NULL, FECHA DATE NOT NULL, VALOR DOUBLE NOT NULL, IDMUNICIPIO INT NOT NULL, IDINDICADOR INT NOT NULL, PRIMARY KEY(IDMUNICIPIOINDICADOR), FOREIGN KEY(IDMUNICIPIO) REFERENCES MUNICIPIO(IDMUNICIPIO), FOREIGN KEY(IDINDICADOR) REFERENCES INDICADOR(IDINDICADOR));

SHOW TABLES;

insert into ESTADO VALUES(2, 'YUCATAN', 20000);

insert into ESTADO VALUES(3, 'HIDALGO', 25000);